### PR TITLE
Fix NERON'S CORE

### PR DESCRIPTION
**Pull request by Bonbons**
Fix NERON'S CORE by ignore case

### CODE REVIEW

**Comment by badconker** [comment]
Thank you for your help but i prefer correct the translation rather than edit code. ;) I suppose, the correct string is : "NERON's Core ?". See : aaf1790c5b399d8f85941d8036c9373ee3b4ce6c

**Comment by Bonbons** [comment]
No in engish the correct string is "NERON'S CORE", all cap.
And in french is "Coeur de NERON", different cap.

**Comment by Bonbons** [comment]
So ignore case for translation is best way.

**Comment by badconker** [comment]
Ok i fixed translation and add case insensitive option to be safe :)

Nevertheless, I have not be able to use your pull request because it target the wrong branch. You must use dev branch

**Pull request closed without merging**
