### PR TITLE
Minor translation fixes in the message manager tabs

### PR DESCRIPTION
**Pull request by Whitellama**
This appears to be a lot of changes but it's actually very few. `po_update` changed lot of the line number comments and for some reason it removed all of the `*/` at the end of the translator comments. I didn't bother fixing that, but if they serve a purpose I'm willing.

**Changes:**
* Translated tab titles in the message manager (statistics, new messages, search messages, favorites, mush channel, private channels)
* Tweaked the Mush Channel and Discussion tabs' tooltips so that they match the game's tooltips

### CODE REVIEW

**Comment by Whitellama** [comment]
I'm not sure whether you want it or not, but I also threw in po_update as a shell script to ease translation for OSX/Linux/*nix users. It's not that different, just switched backslashes to forwardslashes and added a line to put backslashes back into the line number comments. (Running po_update on Linux caused all of the line number comments to show ../CTRLW.user.js instead of ..\CTRLW.user.js. The difference is insignificant but I thought it would be annoying to change so many lines unnecessarily.)

Then again, it's pretty simple to run po_update.bat in non-windows OS, so if you want me to I can remove it. Up to you!

**Comment by badconker** [comment]
Arf sorry , i have forgotten to merge translations branch recently modified into dev branch... Can you update your pull request ? */ was a bug and it was already fixed. I used an old version of xgettext. More over i added "--no-wrap" option in bat file. Your shell file is a good idea :smiley:.

**Comment by Whitellama** [comment]
No worries, I didn't even notice there was a translation branch. I'll update it tomorrow.

**Comment by Whitellama** [comment]
Okay, should be all good now. (I also added --no-wrap to po_update.sh).

**Comment by badconker** [comment]
perfect :)

**Pull request merged**
