### PR TITLE
Update CTRLW.user.js

### PR DESCRIPTION
**Pull request by Javiernh**
Languaje flag on ship. It has a css problem on casting ships

### CODE REVIEW

**Comment by badconker** [comment]
Thank you to try to participate to this project, but there are a lot of mistakes. Have you tried to run your code before submit it ?
Main.k.lang is used before it was defined. Same thing for Main.k.css. Why a h3 tag ? Your td is not in a tr and table tag... Your img tags are not closed...

Sorry but i can't merge this pull request :/

**Comment by Javiernh** [comment]
Yes, I run the code in Tampermonkey and it works. If you say that have many error I believe you because I'm a autodidact. Sorry for errors, I'll try to correct them. Be patient. :)

**Comment by badconker** [comment]
No problem ;). Personnaly i test always on Firefox and for the moment it has always worked on chrome too. On Firefox you can edit directly the js file in the profile directory too, it goes faster too debug, you have just to refresh the web page whereas with tampermonkey, you must reinstall the script for each modification.

**Comment by Javiernh** [comment]
When you say "Your img tags are not closed" what do you mean? How I close img tag? 
I recognize that the "flag" it isn't a nice work. I did it for use by a friend that plays in english and spanish server. :)

**Comment by badconker** [comment]
It was about the ending slash .
Nevertheless i juste realize that it's an old xhtml practice and both  and  are valid in HTML 5. :)

**Pull request closed without merging**
